In [6]:
import numpy as np

In [14]:
class Heap:
    def __init__(self, n):
        self.array = np.zeros(n)
        self.arg = np.zeros(n, dtype=int)
        self.n = n
        self._count = 0
        
    @property
    def count(self):
        return self._count
        
    def add(self, v, idx):
        i = self._count
        self.array[i] = v
        self.arg[i] = idx
        self._count += 1
        parent = int((i - 1) / 2)
        while i > 0 and self.array[parent] < self.array[i]:
            self.array[i], self.array[parent] = self.array[parent], self.array[i]
            self.arg[i], self.arg[parent] = self.arg[parent], self.arg[i]
            i = parent
            parent = int((i - 1) / 2)
        return i
            
    def pop(self):
        self.array[0] = self.array[self._count - 1]
        self.arg[0] = self.arg[self._count - 1]
        
        self._count -= 1
        self.array[self._count] = 0
        i = 0
        largest = i
        
        while True:
            left = 2 * i + 1
            right = left + 1
            if left < self._count and self.array[left] >= self.array[largest]:
                largest = left
            if right < self._count and self.array[right] >= self.array[largest]:
                largest = right
            
            if largest != i:
                self.array[i], self.array[largest] = self.array[largest], self.array[i]
                self.arg[i], self.arg[largest] = self.arg[largest], self.arg[i]
                i = largest
            else:
                break
                
    def add_clip(self, v, idx):
        if self._count < self.n:
            return self.add(v, idx)
        elif self.array[0] > v:
            self.pop()
            return self.add(v, idx)

In [15]:
values = np.random.randint(1000, size=500).astype(float)

In [23]:
h = Heap(50)
tt = np.zeros(50)
for i, v in enumerate(values):
    p = h.add_clip(v, i)
    if p is not None:
        tt[p] = i
np.sort(h.arg)

array([  1,   9,  29,  48,  69,  74,  98, 103, 104, 106, 117, 148, 156,
       164, 167, 168, 194, 212, 230, 240, 247, 250, 264, 269, 270, 276,
       293, 317, 330, 339, 364, 370, 390, 398, 406, 408, 410, 421, 427,
       429, 442, 450, 453, 457, 461, 472, 475, 479, 491, 492])

In [24]:
np.sort(np.argpartition(values, 50)[:50])

array([  1,   9,  29,  48,  69,  74,  98, 103, 104, 106, 117, 148, 156,
       164, 167, 168, 194, 212, 230, 240, 247, 250, 264, 269, 270, 276,
       293, 317, 330, 339, 364, 370, 390, 398, 406, 408, 410, 421, 427,
       429, 442, 450, 453, 457, 461, 472, 475, 479, 491, 492])

In [25]:
tt

array([483.,  41., 331.,  37.,  19., 492.,  28.,  31.,  36.,  39.,   0.,
       461.,  12.,   0.,  30.,  32.,  33.,   0.,  18.,  40.,   0.,  43.,
        45.,  47., 450.,   0.,  26.,  27.,   0.,  29.,   0.,   0.,   0.,
         0.,  34.,  35.,   0.,   0.,  38.,   0.,   0.,   0.,  42.,   0.,
        44.,   0.,  46.,   0.,  48., 479.])

In [26]:
h.arg

array([461, 370, 103, 104, 240, 492, 148, 408, 450, 194, 406, 491,  69,
       168, 156,   1, 317, 293, 442, 453,  98, 270, 117,  48,  74, 247,
       479, 106, 364,  29, 475, 429, 330, 276, 410, 339, 457, 269, 390,
         9, 230, 427, 212, 421, 167, 164, 250, 264, 398, 472])

In [31]:
h = Heap(50)
print(h.add(10, 10))
print(h.add(20, 20))
print(h.add(3, 3))
print(h.add(50, 50))
h.arg

0
0
2
0


array([50, 20,  3, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])